services:
  identity.api:
    image: identity.api
    build:
      context: .
      dockerfile: services/IdentityService/Identity.Api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000

  hotel-catalog.api:
    image: hotel-catalog.api
    build:
      context: .
      dockerfile: services/HotelCatalogService/HotelCatalog.Api/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001

  profile.api:
    image: profile.api
    build:
      context: .
      dockerfile: services/ProfileService/Profile.Api/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://+:5002  

  booking.gateway:
    image: booking.gateway
    build:
      context: .
      dockerfile: gateway/Booking.Gateway/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - identity.api
      - profile.api
      - keycloak
      - hotel-catalog.api
    environment:
      - ASPNETCORE_URLS=http://+:80
  
  keycloak:
    container_name: keycloak
    restart: on-failure
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: booking
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    command: start-dev
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/keycloak/data

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    
  smtp:
    image: mailhog/mailhog
    container_name: mailhog
    restart: on-failure
    ports:
      - "1025:1025"   
      - "8025:8025"   
    volumes:
      - mailhog_data:/data

volumes:
  keycloak_data:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:  
  mailhog_data:
  booking.gateway:

